global:
  # How often Prometheus scrapes metrics
  scrape_interval: 15s
  # How often alert rules are evaluated
  evaluation_interval: 15s

scrape_configs:
  # Prometheus monitoring itself
  - job_name: "prometheus"
    static_configs:
      - targets:
          # Service name + port from docker-compose
          - "prometheus:9090"
  # Host machine metrics via node-exporter
  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: "pilot"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "pilot:8080"
